FROM fopina/misc:bubbles-arm-builder-arch-base

RUN pacman-key --init
RUN pacman-key --populate archlinuxarm
RUN pacman -S --noconfirm go base-devel

RUN useradd temp
RUN curl -L https://aur.archlinux.org/cgit/aur.git/snapshot/libiconv.tar.gz -o /libiconv.tgz && \
	tar xf libiconv.tgz && rm libiconv.tgz && \
	chown -R temp /libiconv && \
	su temp -c "cd /libiconv; makepkg -A"
